09:41:49 - INFO -Started server process [9] (server.py:75)
09:41:49 - INFO -Waiting for application startup. (on.py:45)
09:41:49 - INFO -Application startup complete. (on.py:59)
09:56:16 - INFO -Started server process [9] (server.py:75)
09:56:16 - INFO -Waiting for application startup. (on.py:45)
09:56:16 - INFO -Application startup complete. (on.py:59)
10:01:33 - INFO -172.20.0.7:34376 - "GET /api_goszakup?iin_bin=141040028436 HTTP/1.1" 200 (httptools_impl.py:437)
10:01:33 - ERROR -Elicense error status_code 403 (api_elicense_parser.py:22)
10:01:33 - INFO -172.20.0.7:34400 - "GET /elicense?bin=141040028436 HTTP/1.1" 200 (httptools_impl.py:437)
10:01:34 - INFO -172.20.0.7:34388 - "GET /api_goszakup_unrelaible?iin_bin=141040028436 HTTP/1.1" 200 (httptools_impl.py:437)
10:08:20 - INFO -172.20.0.7:34402 - "GET /api_payments?bin=141040028436&start_date=2022-01-01 HTTP/1.1" 500 (httptools_impl.py:437)
10:08:20 - ERROR -Exception in ASGI application
 (httptools_impl.py:375)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 372, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 261, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 162, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.10/site-packages/starlette/concurrency.py", line 39, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/usr/local/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/api_app/./main.py", line 70, in api_payments
    return api_payments_parser(bin, start_date,)
  File "/home/api_app/./parsers/api_payments_parser.py", line 28, in api_payments_parser
    return api_payments_parser(bin, start_date, try_counts)
  File "/home/api_app/./parsers/api_payments_parser.py", line 28, in api_payments_parser
    return api_payments_parser(bin, start_date, try_counts)
  File "/home/api_app/./parsers/api_payments_parser.py", line 29, in api_payments_parser
    return payments_filter(response.text)
  File "/home/api_app/./filters/payments_filter.py", line 7, in payments_filter
    tmp = xmltodict.parse(xml)
  File "/usr/local/lib/python3.10/site-packages/xmltodict.py", line 327, in parse
    parser.Parse(xml_input, True)
xml.parsers.expat.ExpatError: mismatched tag: line 6, column 2
10:14:38 - INFO -172.20.0.7:32920 - "GET /api_goszakup?iin_bin=141040028436 HTTP/1.1" 200 (httptools_impl.py:437)
10:14:39 - INFO -172.20.0.7:32918 - "GET /api_goszakup_unrelaible?iin_bin=141040028436 HTTP/1.1" 200 (httptools_impl.py:437)
10:14:39 - ERROR -Elicense error status_code 403 (api_elicense_parser.py:22)
10:14:39 - INFO -172.20.0.7:32956 - "GET /elicense?bin=141040028436 HTTP/1.1" 200 (httptools_impl.py:437)
10:19:12 - INFO -Started server process [8] (server.py:75)
10:19:12 - INFO -Waiting for application startup. (on.py:45)
10:19:12 - INFO -Application startup complete. (on.py:59)
10:27:26 - INFO -172.20.0.17:41706 - "GET /api_goszakup?iin_bin=141040028436 HTTP/1.1" 200 (httptools_impl.py:437)
10:27:26 - ERROR -Elicense error status_code 403 (api_elicense_parser.py:22)
10:27:26 - INFO -172.20.0.17:41732 - "GET /elicense?bin=141040028436 HTTP/1.1" 200 (httptools_impl.py:437)
10:27:26 - INFO -172.20.0.17:41708 - "GET /api_goszakup_unrelaible?iin_bin=141040028436 HTTP/1.1" 200 (httptools_impl.py:437)
10:27:26 - INFO -172.20.0.17:41746 - "GET /api_payments?bin=141040028436&start_date=2022-01-01 HTTP/1.1" 200 (httptools_impl.py:437)
10:30:03 - INFO -172.20.0.17:43622 - "GET /api_goszakup?iin_bin=071140021902 HTTP/1.1" 200 (httptools_impl.py:437)
10:30:03 - ERROR -Elicense error status_code 403 (api_elicense_parser.py:22)
10:30:03 - INFO -172.20.0.17:43652 - "GET /elicense?bin=071140021902 HTTP/1.1" 200 (httptools_impl.py:437)
10:30:04 - INFO -172.20.0.17:43614 - "GET /api_goszakup_unrelaible?iin_bin=071140021902 HTTP/1.1" 200 (httptools_impl.py:437)
10:30:07 - INFO -172.20.0.17:43636 - "GET /api_payments?bin=071140021902&start_date=2022-01-01 HTTP/1.1" 200 (httptools_impl.py:437)
10:33:58 - INFO -Started server process [9] (server.py:75)
10:33:58 - INFO -Waiting for application startup. (on.py:45)
10:33:58 - INFO -Application startup complete. (on.py:59)
10:34:01 - INFO -172.20.0.18:59512 - "GET /api_payments?bin=071140021902&start_date=2022-01-01 HTTP/1.1" 200 (httptools_impl.py:437)
10:34:01 - INFO -172.20.0.18:59510 - "GET /api_goszakup?iin_bin=071140021902 HTTP/1.1" 200 (httptools_impl.py:437)
10:34:01 - ERROR -Elicense error status_code 403 (api_elicense_parser.py:22)
10:34:01 - INFO -172.20.0.18:59528 - "GET /elicense?bin=071140021902 HTTP/1.1" 200 (httptools_impl.py:437)
10:34:02 - INFO -172.20.0.18:59516 - "GET /api_goszakup_unrelaible?iin_bin=071140021902 HTTP/1.1" 200 (httptools_impl.py:437)
10:34:43 - INFO -172.20.0.18:44220 - "GET /api_payments?bin=071140021902&start_date=2022-01-01 HTTP/1.1" 200 (httptools_impl.py:437)
10:34:44 - INFO -172.20.0.18:44190 - "GET /api_goszakup?iin_bin=071140021902 HTTP/1.1" 200 (httptools_impl.py:437)
10:34:44 - ERROR -Elicense error status_code 403 (api_elicense_parser.py:22)
10:34:44 - INFO -172.20.0.18:44218 - "GET /elicense?bin=071140021902 HTTP/1.1" 200 (httptools_impl.py:437)
10:34:45 - INFO -172.20.0.18:44204 - "GET /api_goszakup_unrelaible?iin_bin=071140021902 HTTP/1.1" 200 (httptools_impl.py:437)
15:46:56 - INFO -Started server process [9] (server.py:75)
15:46:56 - INFO -Waiting for application startup. (on.py:45)
15:46:56 - INFO -Application startup complete. (on.py:59)
16:31:11 - INFO -172.20.0.23:46740 - "GET /api_goszakup?iin_bin=190341004451 HTTP/1.1" 200 (httptools_impl.py:437)
16:31:12 - INFO -172.20.0.23:46760 - "GET /api_goszakup_unrelaible?iin_bin=190341004451 HTTP/1.1" 200 (httptools_impl.py:437)
16:31:14 - INFO -172.20.0.23:46746 - "GET /api_payments?bin=190341004451&start_date=2000-01-01 HTTP/1.1" 200 (httptools_impl.py:437)
16:31:14 - INFO -172.20.0.23:46748 - "GET /elicense?bin=190341004451 HTTP/1.1" 200 (httptools_impl.py:437)
16:39:32 - INFO -172.20.0.23:35874 - "GET /api_goszakup?iin_bin=980741000528 HTTP/1.1" 200 (httptools_impl.py:437)
16:39:33 - INFO -172.20.0.23:35886 - "GET /api_goszakup_unrelaible?iin_bin=980741000528 HTTP/1.1" 200 (httptools_impl.py:437)
16:39:33 - INFO -172.20.0.23:35898 - "GET /api_payments?bin=980741000528&start_date=2000-01-01 HTTP/1.1" 200 (httptools_impl.py:437)
16:39:33 - INFO -172.20.0.23:35914 - "GET /elicense?bin=980741000528 HTTP/1.1" 200 (httptools_impl.py:437)
